# Generated by Django 6.0 on 2026-03-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evan', '0002_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='repeat_interval_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='repeat_times_per_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='repeat_type',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('interval', 'Interval')], default='none', max_length=20),
        ),
    ]
