# Generated by Django 6.0 on 2026-03-01 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evan', '0003_topic_repeat_interval_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='repeat_times_per_week',
        ),
    ]
