# Generated by Django 6.0 on 2026-03-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evan', '0004_remove_topic_repeat_times_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='last_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='next_active_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='weekly_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='weekly_target',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
