# Generated by Django 6.0 on 2026-03-06 00:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evan', '0006_dailyactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
