# Generated by Django 6.0 on 2026-03-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evan', '0007_dailyactivity_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
