# Generated by Django 6.0 on 2026-03-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evan', '0008_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.CharField(choices=[('important', 'Important'), ('attention', 'Needs Attention'), ('reference', 'Reference')], default='reference', max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='tag',
            field=models.CharField(choices=[('important', 'Important'), ('attention', 'Needs Attention'), ('reference', 'Reference')], default='important', max_length=20),
        ),
        migrations.AddField(
            model_name='track',
            name='tag',
            field=models.CharField(choices=[('important', 'Important'), ('attention', 'Needs Attention'), ('reference', 'Reference')], default='important', max_length=20),
        ),
    ]
