# Generated by Django 6.0 on 2026-03-26 15:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evan', '0010_activitylog_delete_dailyactivity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activitylog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('note_create', 'Note Created'), ('note_edit', 'Note Edited'), ('topic_update', 'Topic Updated'), ('topic_complete', 'Topic Completed'), ('explanation', 'Feynman Explanation'), ('journal', 'Journal Entry')], default='note_create', max_length=50),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='actions_count',
        ),
    ]
